<?php

/**
 * @file
 * Contains book_tree.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function book_tree_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the book_tree module.
    case 'help.page.book_tree':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Collapsible book navigation block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function book_tree_theme() {
  return [
    'book_tree_block' => [
      'variables' => ['items' => [], 'attributes' => [], 'active_trail' => []],
    ],
  ];
}
